export const QUIZ_ACTIONS = {
  START_EXAM: 'START_EXAM',

  RESET_EXAM: 'RESET_EXAM',

  SET_TIMER: 'SET_TIMER',

  SET_QUESTION_COUNT: 'SET_QUESTION_COUNT',

  LOAD_SESSION: 'LOAD_SESSION',

  NEXT_QUESTION: 'NEXT_QUESTION',

  PREVIOUS_QUESTION: 'PREVIOUS_QUESTION',

  SELECT_ANSWER: 'SELECT_ANSWER',

  TOGGLE_BOOKMARK: 'TOGGLE_BOOKMARK',

  TICK_TIMER: 'TICK_TIMER',

  SUBMIT_EXAM: 'SUBMIT_EXAM',

  GO_TO_QUESTION: 'GO_TO_QUESTION',

  SET_RESULT: 'SET_RESULT',

  SET_REVIEW_INDEX: 'SET_REVIEW_INDEX',

  NEXT_REVIEW: 'NEXT_REVIEW',

  PREVIOUS_REVIEW: 'PREVIOUS_REVIEW',

  PAUSE_TIMER: 'PAUSE_TIMER',

  RESUME_TIMER: 'RESUME_TIMER',
};
